server:
  forward-headers-strategy: framework

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/motioncad}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write_dates_as_timestamps: false
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:your-access-key}
      secret-key: ${AWS_SECRET_KEY:your-secret-key}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    s3:
      bucket: ${AWS_S3_BUCKET:motioncad-assets}
      stack:
        auto: false
